### PR TITLE
Add conda installation doc

### PR DESCRIPTION
**Pull request by aulemahal**
Hi!

This PR adds a bit of documentation on how to install SBCK in a conda environment. It also adds a mention of the needed C++ compiler for installing the python version.

### CODE REVIEW

**Comment by fangwangwf** [comment]
Hi,

I have tried these below:

conda create -n sbck eigen numpy scipy pybind11 cxx-compiler
conda activate sbck
python3 setup.py install --user

But the following error is still there:
>>> import SBCK as bc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/glade/work/fangwang/MBCn/SBCK-python/SBCK/__init__.py", line 25, in <module>
    from .__QM     import QM
  File "/glade/work/fangwang/MBCn/SBCK-python/SBCK/__QM.py", line 27, in <module>
    from .tools.__Dist import _Dist
  File "/glade/work/fangwang/MBCn/SBCK-python/SBCK/tools/__init__.py", line 21, in <module>
    from .__tools_cpp             import SparseHist
ModuleNotFoundError: No module named 'SBCK.tools.__tools_cpp'

Anything else I need to add? Thank you!

**Comment by aulemahal** [comment]
Did you execute the "import SBCK as bc" line from the python folder of the repo ?

I'll add a note because I stumbled on the same issue!

This should work:
```bash
conda create -n sbck eigen numpy scipy pybind11 cxx-compiler
conda activate sbck
python setup.py install   # no need for --user in a conda env
cd # get out of the source folder
python -c "import SBCK"
```

The `install` line will install compiled files in the python folder, NOT in the current source folder. But if you execute the last line from the source folder, python will actually try to import the source itself and not the installed version.

**Comment by fangwangwf** [comment]
Hi,

Thank you very much for helping me. After getting out of the source folder and the error disappeared!

Best Regards,
Fang

From: Pascal Bourgault ***@***.***>
Date: Friday, March 24, 2023 at 3:47 PM
To: yrobink/SBCK ***@***.***>
Cc: Fang Wang ***@***.***>, Comment ***@***.***>
Subject: [EXT] Re: [yrobink/SBCK] Add conda installation doc (PR #5)
CAUTION: Email Originated Outside of Auburn.

Did you execute the "import SBCK as bc" line from the python folder of the repo ?

I'll add a note because I stumbled on the same issue!

This should work:

conda create -n sbck eigen numpy scipy pybind11 cxx-compiler

conda activate sbck

python setup.py install   # no need for --user in a conda env

cd # get out of the source folder

python -c "import SBCK"

The install line will install compiled files in the python folder, NOT in the current source folder. But if you execute the last line from the source folder, python will actually try to import the source itself and not the installed version.

**Comment by yrobink** [comment]
Dear @aulemahal ,

Thanks for your help

**Pull request merged**
